// <auto-generated />
namespace Amazon.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ajout_historiqueheure : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ajout_historiqueheure));
        
        string IMigrationMetadata.Id
        {
            get { return "201906040819403_ajout_historique+heure"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
